import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Calendar, Camera, Gift, Bell, User, Menu, Sparkles, Star, Check, CreditCard, MessageCircle, BarChart3, LogOut, ShieldCheck, Plus, X, Image as ImageIcon } from 'lucide-react';
import './styles.css';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:4000';

const fallbackServices = [
  { id: 'basic', name: 'Manicure básica', description: 'Limpieza, limado, cutícula e hidratación.', price: 40, duration: 45, category: 'manicure', image_url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=500&q=80' },
  { id: 'spa', name: 'Manicure spa', description: 'Exfoliación, masaje y esmaltado premium.', price: 65, duration: 70, category: 'manicure', image_url: 'https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=500&q=80' },
  { id: 'gel', name: 'Gel permanente', description: 'Color de larga duración con brillo profesional.', price: 60, duration: 75, category: 'gel', image_url: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=500&q=80' },
  { id: 'acrylic', name: 'Acrílicas', description: 'Extensiones resistentes con forma personalizada.', price: 80, duration: 110, category: 'uñas', image_url: 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=500&q=80' },
  { id: 'softgel', name: 'Soft Gel', description: 'Extensiones ligeras, flexibles y modernas.', price: 60, duration: 90, category: 'uñas', image_url: 'https://images.unsplash.com/photo-1599948128020-9a44505b0d1b?auto=format&fit=crop&w=500&q=80' },
  { id: 'nailart', name: 'Nail Art', description: 'Decoración artística, relieves, piedras y efectos.', price: 30, duration: 50, category: 'decoración', image_url: 'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=500&q=80' },
];
const specialists = [{ id: 1, full_name: 'Valeria Torres' }, { id: 2, full_name: 'Daniela Ruiz' }, { id: 3, full_name: 'Camila Prado' }];
const demoUsers = {
  '00000001': { id: 1, dni: '00000001', full_name: 'Súper Admin Nail Beauty', role: 'SA', loyalty_points: 0, password: 'Admin123!' },
  '00000002': { id: 2, dni: '00000002', full_name: 'Dueña Nail Beauty', role: 'OWNER', loyalty_points: 0, password: 'Duena123!' },
  '00000003': { id: 3, dni: '00000003', full_name: 'Andrea Cliente', role: 'USER', loyalty_points: 250, password: 'Andrea123!' },
};
const seedBookings = [
  { id: 1, date: '2026-07-08', time: '15:00', serviceId: 'gel', specialistId: 1, status: 'confirmed', userName: 'Andrea Cliente', price: 60 },
  { id: 2, date: '2026-07-11', time: '16:30', serviceId: 'acrylic', specialistId: 2, status: 'pending', userName: 'Andrea Cliente', price: 80 },
];

async function api(path, options = {}) {
  const token = localStorage.getItem('nb_token');
  const headers = options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' };
  const res = await fetch(`${API_URL}${path}`, { ...options, headers: { ...headers, ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || 'Error de conexión');
  return data;
}

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('nb_user') || 'null'));
  const [view, setView] = useState('inicio');
  const [services, setServices] = useState(fallbackServices);
  const [bookings, setBookings] = useState(() => JSON.parse(localStorage.getItem('nb_bookings') || 'null') || seedBookings);
  const [quote, setQuote] = useState(null);

  React.useEffect(() => { api('/api/services').then(rows => rows.length && setServices(rows)).catch(() => {}); }, []);
  React.useEffect(() => localStorage.setItem('nb_bookings', JSON.stringify(bookings)), [bookings]);

  function saveSession(nextUser, token = 'demo-token') {
    localStorage.setItem('nb_user', JSON.stringify(nextUser));
    localStorage.setItem('nb_token', token);
    setUser(nextUser); setView('inicio');
  }
  function logout() { localStorage.removeItem('nb_user'); localStorage.removeItem('nb_token'); setUser(null); }
  function addBooking(booking) { setBookings(prev => [{ id: Date.now(), userName: user.full_name, status: 'confirmed', ...booking }, ...prev]); setView('reservas'); }

  if (!user) return <AuthScreen saveSession={saveSession} />;
  return <main className="shell"><Sidebar user={user} view={view} setView={setView} logout={logout}/><section className="workspace"><Topbar user={user} setView={setView}/><Dashboard view={view} setView={setView} user={user} services={services} bookings={bookings} setBookings={setBookings} quote={quote} setQuote={setQuote} addBooking={addBooking}/></section></main>;
}

function AuthScreen({ saveSession }) {
  const [mode, setMode] = useState('login'); const [error, setError] = useState(''); const [form, setForm] = useState({ dni: '00000003', password: 'Andrea123!', fullName: '', birthDate: '', phone: '', email: '' });
  async function submit(e) { e.preventDefault(); setError(''); try { if (mode === 'login') { const demo = demoUsers[form.dni]; if (demo && demo.password === form.password) return saveSession(demo); const data = await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ dni: form.dni, password: form.password }) }); saveSession(data.user, data.token); } else { if (!form.dni || !form.fullName || !form.birthDate || !form.phone || !form.password) throw new Error('Completa DNI, nombre, nacimiento, celular y contraseña.'); const next = { id: Date.now(), dni: form.dni, full_name: form.fullName, role: 'USER', loyalty_points: 0 }; try { const data = await api('/api/auth/register', { method: 'POST', body: JSON.stringify(form) }); saveSession(data.user, data.token); } catch { saveSession(next); } } } catch (err) { setError(err.message); } }
  return <main className="auth"><section className="auth-card"><div className="brand big">Nail·Beauty<small>Salón de belleza inteligente</small></div><h1>{mode === 'login' ? 'Inicia sesión' : 'Crea tu cuenta'}</h1><p>Acceso para súper admin, dueña y clientas. Prueba: 00000001/Admin123!, 00000002/Duena123!, 00000003/Andrea123!</p><form onSubmit={submit}>{mode === 'register' && <><input placeholder="Nombre completo" value={form.fullName} onChange={e=>setForm({...form, fullName:e.target.value})}/><input type="date" value={form.birthDate} onChange={e=>setForm({...form, birthDate:e.target.value})}/><input placeholder="Celular" value={form.phone} onChange={e=>setForm({...form, phone:e.target.value})}/><input placeholder="Correo opcional" value={form.email} onChange={e=>setForm({...form, email:e.target.value})}/></>}<input placeholder="DNI" value={form.dni} onChange={e=>setForm({...form, dni:e.target.value})}/><input type="password" placeholder="Contraseña" value={form.password} onChange={e=>setForm({...form, password:e.target.value})}/>{error && <strong className="error">{error}</strong>}<button>{mode === 'login' ? 'Entrar' : 'Registrarme'}</button></form><button className="ghost" onClick={()=>setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Crear cuenta de clienta' : 'Ya tengo cuenta'}</button></section></main>;
}
const nav = [['inicio','Inicio', Calendar], ['reservas','Mis reservas', Calendar], ['cotizar','Cotizar diseño con IA', Camera], ['perfil','Perfil', User], ['pagos','Pagos', CreditCard]];
function Sidebar({ user, view, setView, logout }) { const admin = user.role === 'SA' || user.role === 'OWNER'; return <aside className="sidebar"><div className="brand">Nail·Beauty<small>Salón de belleza</small></div><nav>{[...nav, ...(admin ? [['admin','Panel admin', BarChart3]] : [])].map(([id,n,Icon])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}><Icon size={18}/>{n}{n==='Mis reservas'&&<b>{user.loyalty_points||0}</b>}</button>)}</nav><div className="birthday"><Gift/><h3>Beneficio de cumpleaños</h3><p>Manicure básica gratis o 50% en Nail Art.</p><button onClick={()=>setView('reservas')}>Reservar ahora</button><small>Válido una vez por año</small></div><button className="logout" onClick={logout}><LogOut size={17}/> Salir</button></aside>; }
function Topbar({ user, setView }) { return <header className="topbar"><button className="hamb"><Menu/></button><a onClick={()=>setView('inicio')}>Inicio</a><a onClick={()=>setView('reservas')}>Reservar</a><a onClick={()=>setView('cotizar')}>IA</a><a onClick={()=>setView('perfil')}>Perfil</a><span/><Bell/><div className="avatar">{user.full_name?.[0] || 'N'}</div><strong>Hola, {user.full_name?.split(' ')[0]}</strong></header>; }
function Dashboard(props) { if (props.view === 'reservas') return <BookingPage {...props}/>; if (props.view === 'cotizar') return <AiPage {...props}/>; if (props.view === 'perfil') return <Profile {...props}/>; if (props.view === 'pagos') return <Payments {...props}/>; if (props.view === 'admin') return <Admin {...props}/>; return <Home {...props}/>; }
function Home({ setView, services, bookings, user }) { return <div className="grid"><section className="hero"><div><h1>Reserva tu cita</h1><p>Elige servicio, especialista y horario disponible. Tu cita queda bloqueada automáticamente.</p><button onClick={()=>setView('reservas')}>Reservar ahora <Calendar size={18}/></button></div></section><AiBox setView={setView}/><section className="card list"><h2>Próximas reservas <a onClick={()=>setView('reservas')}>Ver todas</a></h2>{bookings.slice(0,3).map(b=><BookingCard key={b.id} b={b} services={services}/>)}</section><Catalog services={services}/><AiAssistant/><section className="why"><h2>Tu nivel: {user.loyalty_points >= 250 ? 'Oro' : 'Inicial'}</h2>{['Cotización IA','Recordatorios','Pagos Yape/Plin','Beneficios'].map(x=><span key={x}><Sparkles/>{x}</span>)}</section></div>; }
function AiBox({ setView }) { return <section className="card quote"><h2>Cotiza tu diseño con IA <Sparkles size={18}/></h2><p>Sube una imagen o describe tu diseño para recibir precio, duración y materiales.</p><div className="upload"><Camera/><b>Subir imagen</b><small>o arrastra tu imagen aquí</small></div><button onClick={()=>setView('cotizar')}>Cotizar con IA</button></section>; }
function BookingPage({ services, bookings, setBookings, addBooking }) { const [form, setForm] = useState({ serviceId: services[0]?.id, specialistId: 1, date: '2026-07-08', time: '10:00', payment: 'seña' }); const selected = services.find(s=>s.id===form.serviceId) || services[0]; const taken = new Set(bookings.map(b=>`${b.date}-${b.time}-${b.specialistId}`)); const slots = ['09:00','10:00','11:30','15:00','16:30','18:00']; return <div className="two"><section className="card"><h2>Nueva reserva <Calendar/></h2><div className="formgrid"><label>Servicio<select value={form.serviceId} onChange={e=>setForm({...form, serviceId:e.target.value})}>{services.map(s=><option value={s.id}>{s.name} - S/ {s.price}</option>)}</select></label><label>Especialista<select value={form.specialistId} onChange={e=>setForm({...form, specialistId:Number(e.target.value)})}>{specialists.map(s=><option value={s.id}>{s.full_name}</option>)}</select></label><label>Fecha<input type="date" value={form.date} onChange={e=>setForm({...form, date:e.target.value})}/></label><label>Pago<select value={form.payment} onChange={e=>setForm({...form, payment:e.target.value})}><option value="local">Pago en local</option><option value="seña">Seña para confirmar</option><option value="yape">Yape</option><option value="plin">Plin</option><option value="card">Tarjeta</option></select></label></div><h3>Horarios disponibles</h3><div className="slots">{slots.map(t=>{const disabled=taken.has(`${form.date}-${t}-${form.specialistId}`); return <button disabled={disabled} className={form.time===t?'active':''} onClick={()=>!disabled&&setForm({...form,time:t})}>{t}{disabled?' ocupado':''}</button>})}</div><div className="summary"><b>Resumen</b><span>{selected?.name}</span><span>{specialists.find(s=>s.id===form.specialistId)?.full_name}</span><span>{form.date} {form.time}</span><strong>S/ {selected?.price}</strong></div><button onClick={()=>addBooking({ ...form, price: selected?.price, serviceId: selected?.id })}>Confirmar reserva</button></section><section className="card list"><h2>Mis reservas</h2>{bookings.map(b=><BookingCard key={b.id} b={b} services={services} actions onCancel={()=>setBookings(bookings.map(x=>x.id===b.id?{...x,status:'cancelled'}:x))}/>)}</section></div>; }
function AiPage({ quote, setQuote, addBooking, services }) { const [hints, setHints] = useState('acrílico con piedras y efecto espejo para boda'); const [image, setImage] = useState(null); const [loading, setLoading] = useState(false); async function makeQuote(){ setLoading(true); const form = new FormData(); form.append('hints', hints); if (image) form.append('image', image); try { setQuote(await api('/api/quotes/ai', { method:'POST', body: form })); } catch { const alta=/piedra|3d|boda|relieve/i.test(hints); setQuote({ difficulty: alta?'Alta':'Media', estimatedMinutes: alta?135:95, price: alta?150:95, materials: ['Acrílico','Nail Art','Esmalte permanente', alta?'Piedras':'Brillo'], explanation: 'Demo local: configura GEMINI_API_KEY en el backend para analizar con Gemini.', requiresReview: alta, source:'demo' }); } finally { setLoading(false); } } return <div className="two"><section className="card quote"><h2>Cotizar diseño con IA <Sparkles/></h2><textarea value={hints} onChange={e=>setHints(e.target.value)} placeholder="Describe colores, evento, piedras, largo o sube una imagen."/><label className="upload file-upload"><ImageIcon/><b>{image ? image.name : 'Imagen referencial'}</b><small>Gemini puede analizar foto + descripción.</small><input type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0] || null)}/></label><button onClick={makeQuote} disabled={loading}>{loading ? 'Analizando con IA...' : 'Analizar diseño'}</button></section>{quote && <section className="card result"><h2>Resultado de tu cotización <span>{quote.source === 'gemini' ? 'Gemini ✨' : 'IA ✨'}</span></h2><img src={image ? URL.createObjectURL(image) : 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=700&q=80'}/>{quote.aiWarning && <small className="ai-warning">{quote.aiWarning}</small>}<p>Nivel de dificultad <b>{quote.difficulty}</b></p><p>Tiempo estimado <b>{Math.floor(quote.estimatedMinutes/60)}h {quote.estimatedMinutes%60}m</b></p><p>Precio aproximado <strong>S/ {quote.price}</strong></p><div className="checks">{quote.materials.map(x=><span key={x}><Check size={16}/>{x}</span>)}</div><p>{quote.explanation}</p><button onClick={()=>addBooking({ date:'2026-07-09', time:'15:00', specialistId:1, serviceId:'nailart', price:quote.price, quote })}>Reservar este diseño</button></section>}</div>; }

function AiAssistant() { const [message, setMessage] = useState('¿Qué diseño recomiendas para una boda?'); const [reply, setReply] = useState('Para una boda recomiendo soft gel nude con brillo perlado y una decoración sutil.'); const [loading, setLoading] = useState(false); async function ask(){ if(!message.trim()) return; setLoading(true); try { const data = await api('/api/assistant', { method:'POST', body: JSON.stringify({ message }) }); setReply(data.aiWarning ? `${data.reply} (${data.aiWarning})` : data.reply); } catch { setReply('Puedo ayudarte con precios, horarios y diseños. Configura GEMINI_API_KEY para activar respuestas inteligentes en vivo.'); } finally { setLoading(false); } } return <section className="card result chat"><h2>Asistente virtual <MessageCircle/></h2><p>{reply}</p><div className="chat-row"><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Pregúntame por precios, horarios o diseños"/><button onClick={ask} disabled={loading}>{loading ? '...' : 'Enviar'}</button></div></section>; }

function BookingCard({ b, services, actions, onCancel }) { const s = services.find(x=>x.id===b.serviceId) || {}; const d = new Date(`${b.date}T00:00:00`); return <article className="booking"><div className="date"><span>{d.toLocaleString('es-PE',{month:'short'}).toUpperCase()}</span><strong>{String(d.getDate()).padStart(2,'0')}</strong><small>{d.toLocaleString('es-PE',{weekday:'short'}).toUpperCase()}</small></div><img src={s.image_url || fallbackServices[0].image_url}/><div><h4>{s.name || 'Servicio personalizado'}</h4><p>◷ {b.time} · S/ {b.price}</p><small>con {specialists.find(x=>x.id===Number(b.specialistId))?.full_name || 'Especialista'}</small></div><em className={b.status}>{b.status}</em>{actions && b.status !== 'cancelled' && <button className="mini" onClick={onCancel}><X size={14}/> Cancelar</button>}</article>; }
function Catalog({ services }) { return <section className="card catalog"><h2>Catálogo de servicios</h2><div>{services.map(s=><article className="service" key={s.id}><img src={s.image_url || fallbackServices[0].image_url}/><h4>{s.name}</h4><p>S/ {s.price} · {s.duration} min</p><small>{s.description}</small></article>)}</div></section>; }
function Profile({ user, bookings }) { return <div className="two"><section className="card"><h2>Mi perfil <User/></h2><p><b>DNI:</b> {user.dni}</p><p><b>Nombre:</b> {user.full_name}</p><p><b>Rol:</b> {user.role}</p><p><b>Puntos:</b> {user.loyalty_points}</p><progress value={user.loyalty_points || 0} max="500"/><h3>Beneficios disponibles</h3><span className="pill">10% de descuento</span><span className="pill">Cumpleaños anual</span></section><section className="card"><h2>Historial</h2><p>{bookings.length} reservas registradas, pagos y diseños quedarán vinculados al perfil.</p></section></div>; }
function Payments() { return <section className="card"><h2>Pagos <CreditCard/></h2>{['Pago en local','Tarjeta','Yape','Plin','Pago parcial / seña'].map(x=><p className="pay" key={x}><Check/> {x}</p>)}</section>; }
function Admin({ user, services, bookings }) { return <div className="grid admin"><section className="card"><h2>{user.role === 'SA' ? 'Panel Súper Admin' : 'Panel Dueña'} <ShieldCheck/></h2><div className="kpis"><b>{bookings.length}<small>Reservas</small></b><b>S/ {bookings.reduce((a,b)=>a+Number(b.price||0),0)}<small>Ingresos</small></b><b>{services.length}<small>Servicios</small></b><b>92%<small>Asistencia</small></b></div></section><section className="card"><h2>Gestión rápida <Plus/></h2><p>Administrar horarios, manicuristas, promociones, servicios, clientes y reportes IA.</p></section><section className="card list"><h2>Agenda completa</h2>{bookings.map(b=><BookingCard key={b.id} b={b} services={services}/>)}</section><section className="card"><h2>Reporte con IA <BarChart3/></h2><p>La mayor demanda está entre viernes y sábado. Recomendación: promoción de Soft Gel martes y miércoles para equilibrar agenda.</p></section></div>; }

createRoot(document.getElementById('root')).render(<App/>);
