import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Calendar, Camera, Gift, Bell, User, Menu, Sparkles, Check, CreditCard, MessageCircle, BarChart3, LogOut, ShieldCheck, Plus, X, Image as ImageIcon, Users, BriefcaseBusiness } from 'lucide-react';
import './styles.css';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:4000';
const fallbackServices = [
  { id: 'basic', name: 'Manicure básica', description: 'Limpieza, limado, cutícula e hidratación.', price: 40, duration: 45, category: 'Uñas' },
  { id: 'acrylic', name: 'Acrílicas naturales', description: 'Extensión acrílica con acabado natural.', price: 80, duration: 100, category: 'Uñas' },
  { id: 'makeup', name: 'Maquillaje social', description: 'Maquillaje para eventos.', price: 50, duration: 60, category: 'Maquillaje' },
  { id: 'waves', name: 'Peinado con ondas', description: 'Ondas definidas para eventos.', price: 45, duration: 50, category: 'Peinados' },
];
const demoUsers = {
  '00000001': { id: 1, dni: '00000001', full_name: 'Súper Admin Nail Beauty', role: 'SA', password: 'Admin123!' },
  '00000002': { id: 2, dni: '00000002', full_name: 'Dueña Nail Beauty', role: 'OWNER', password: 'Duena123!' },
  '00000003': { id: 3, dni: '00000003', full_name: 'Andrea Cliente', role: 'USER', loyalty_points: 250, password: 'Andrea123!' },
  '90000001': { id: 4, dni: '90000001', full_name: 'Valeria Torres', role: 'WORKER', password: 'Andrea123!' },
};

async function api(path, options = {}) {
  const token = localStorage.getItem('nb_token');
  const headers = options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' };
  const res = await fetch(`${API_URL}${path}`, { ...options, headers: { ...headers, ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || 'Error de conexión');
  return data;
}
function money(v) { return `S/ ${Number(v || 0).toFixed(Number(v || 0) % 1 ? 2 : 0)}`; }
function dateTime(date, time) { return `${date}T${time}:00-05:00`; }

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('nb_user') || 'null'));
  const [view, setView] = useState('inicio');
  const [services, setServices] = useState(fallbackServices);
  const [categories, setCategories] = useState([]);
  const [paymentMethods, setPaymentMethods] = useState([]);
  const [bookings, setBookings] = useState([]);
  const [quote, setQuote] = useState(null);
  const admin = user?.role === 'SA' || user?.role === 'OWNER';

  async function refresh() {
    api('/api/services').then(rows => rows.length && setServices(rows)).catch(() => {});
    api('/api/categories').then(setCategories).catch(() => {});
    api('/api/payment-methods').then(setPaymentMethods).catch(() => {});
    if (user) api('/api/bookings').then(setBookings).catch(() => setBookings([]));
  }
  useEffect(() => { refresh(); }, [user]);
  function saveSession(nextUser, token = 'demo-token') { localStorage.setItem('nb_user', JSON.stringify(nextUser)); localStorage.setItem('nb_token', token); setUser(nextUser); setView('inicio'); }
  function logout() { localStorage.removeItem('nb_user'); localStorage.removeItem('nb_token'); setUser(null); }
  if (!user) return <AuthScreen saveSession={saveSession} />;
  return <main className="shell"><Sidebar user={user} view={view} setView={setView} logout={logout}/><section className="workspace"><Topbar user={user} setView={setView}/><Dashboard {...{view,setView,user,services,setServices,categories,setCategories,paymentMethods,bookings,setBookings,quote,setQuote,refresh,admin}}/></section></main>;
}

function AuthScreen({ saveSession }) {
  const [mode, setMode] = useState('login'); const [error, setError] = useState(''); const [form, setForm] = useState({ dni: '00000003', password: 'Andrea123!', fullName: '', birthDate: '', phone: '', email: '' });
  async function submit(e) { e.preventDefault(); setError(''); try { if (mode === 'login') { try { const data = await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ dni: form.dni, password: form.password }) }); return saveSession(data.user, data.token); } catch (loginError) { const demo = demoUsers[form.dni]; if (demo && demo.password === form.password) return saveSession(demo); throw loginError; } } else { const data = await api('/api/auth/register', { method: 'POST', body: JSON.stringify(form) }); saveSession(data.user, data.token); } } catch (err) { setError(err.message); } }
  return <main className="auth"><section className="auth-card"><div className="brand big">Nail·Beauty<small>Salón inteligente</small></div><h1>{mode === 'login' ? 'Inicia sesión' : 'Crea tu cuenta'}</h1><p>Pruebas: SA 00000001/Admin123!, Dueña 00000002/Duena123!, Trabajadora 90000001/Andrea123!, Cliente 00000003/Andrea123!</p><form onSubmit={submit}>{mode === 'register' && <><input placeholder="Nombre completo" value={form.fullName} onChange={e=>setForm({...form, fullName:e.target.value})}/><input type="date" value={form.birthDate} onChange={e=>setForm({...form, birthDate:e.target.value})}/><input placeholder="Celular" value={form.phone} onChange={e=>setForm({...form, phone:e.target.value})}/><input placeholder="Correo opcional" value={form.email} onChange={e=>setForm({...form, email:e.target.value})}/></>}<input placeholder="DNI / usuario" value={form.dni} onChange={e=>setForm({...form, dni:e.target.value})}/><input type="password" placeholder="Contraseña" value={form.password} onChange={e=>setForm({...form, password:e.target.value})}/>{error && <strong className="error">{error}</strong>}<button>{mode === 'login' ? 'Entrar' : 'Registrarme'}</button></form><button className="ghost" onClick={()=>setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Crear cuenta de clienta' : 'Ya tengo cuenta'}</button></section></main>;
}
const navBase = [['inicio','Inicio', Calendar], ['reservas','Reservas', Calendar], ['cotizar','Cotizar IA', Camera], ['perfil','Perfil', User], ['pagos','Pagos', CreditCard]];
function Sidebar({ user, view, setView, logout }) { const admin = user.role === 'SA' || user.role === 'OWNER'; const worker = user.role === 'WORKER'; const nav = worker ? [['trabajo','Mi trabajo', BriefcaseBusiness], ['perfil','Perfil', User]] : [...navBase, ...(admin ? [['admin','Panel admin', BarChart3], ['trabajadoras','Trabajadoras', Users], ['catalogo','Catálogo', Plus]] : [])]; return <aside className="sidebar"><div className="brand">Nail·Beauty<small>{user.role}</small></div><nav>{nav.map(([id,n,Icon])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}><Icon size={18}/>{n}</button>)}</nav><div className="birthday"><Gift/><h3>Beneficio</h3><p>Reservas, pagos y agenda por rol.</p></div><button className="logout" onClick={logout}><LogOut size={17}/> Salir</button></aside>; }
function Topbar({ user, setView }) { return <header className="topbar"><button className="hamb"><Menu/></button><a onClick={()=>setView('inicio')}>Inicio</a><a onClick={()=>setView(user.role==='WORKER'?'trabajo':'reservas')}>Reservas</a><a onClick={()=>setView('cotizar')}>IA</a><span/><Bell/><div className="avatar">{user.full_name?.[0] || 'N'}</div><strong>Hola, {user.full_name?.split(' ')[0]}</strong></header>; }
function Dashboard(props) { if (props.view === 'trabajo') return <WorkerPanel {...props}/>; if (props.view === 'reservas') return <BookingPage {...props}/>; if (props.view === 'cotizar') return <AiPage {...props}/>; if (props.view === 'perfil') return <Profile {...props}/>; if (props.view === 'pagos') return <Payments {...props}/>; if (props.view === 'admin') return <Admin {...props}/>; if (props.view === 'trabajadoras') return <WorkersAdmin {...props}/>; if (props.view === 'catalogo') return <CatalogAdmin {...props}/>; return <Home {...props}/>; }
function Home({ setView, services, bookings, user }) { return <div className="grid"><section className="hero"><div><h1>Reserva tu cita</h1><p>Elige servicio, trabajadora, método de pago y horario real según duración + 15 minutos de descanso.</p><button onClick={()=>setView(user.role==='WORKER'?'trabajo':'reservas')}>Ver agenda <Calendar size={18}/></button></div></section><AiBox setView={setView}/><section className="card list"><h2>Reservas recientes</h2>{bookings.slice(0,3).map(b=><BookingCard key={b.id} b={b}/>)}</section><Catalog services={services}/><AiAssistant/></div>; }
function AiBox({ setView }) { return <section className="card quote"><h2>Cotiza tu diseño con IA <Sparkles size={18}/></h2><p>Sube una imagen o describe tu diseño para recibir precio, duración y materiales.</p><button onClick={()=>setView('cotizar')}>Cotizar con IA</button></section>; }

function BookingPage({ services, paymentMethods, bookings, setBookings, refresh }) {
  const [specialists, setSpecialists] = useState([]); const [slots, setSlots] = useState([]); const [error, setError] = useState('');
  const [form, setForm] = useState({ serviceId: services[0]?.id, specialistId: '', date: '2026-07-08', time: '', paymentMethodId: '' });
  const selected = services.find(s=>s.id===form.serviceId) || services[0];
  useEffect(()=>{ if (selected) api(`/api/specialists?serviceId=${selected.id}`).then(rows=>{setSpecialists(rows); if(rows[0]) setForm(f=>({...f, specialistId: String(rows[0].id)}));}).catch(()=>setSpecialists([])); }, [form.serviceId, services.length]);
  useEffect(()=>{ if(form.date && form.specialistId && form.serviceId) api(`/api/availability?date=${form.date}&specialistId=${form.specialistId}&serviceId=${form.serviceId}`).then(setSlots).catch(()=>setSlots([])); }, [form.date, form.specialistId, form.serviceId]);
  async function reserve(){ setError(''); try { await api('/api/bookings', { method:'POST', body: JSON.stringify({ serviceId: form.serviceId, specialistId: form.specialistId, startsAt: dateTime(form.date, form.time), paymentMethodId: form.paymentMethodId }) }); await refresh(); } catch(e){ setError(e.message); } }
  return <div className="two"><section className="card"><h2>Nueva reserva <Calendar/></h2>{error && <strong className="error">{error}</strong>}<div className="formgrid"><label>Servicio<select value={form.serviceId} onChange={e=>setForm({...form, serviceId:e.target.value})}>{services.map(s=><option key={s.id} value={s.id}>{s.name} - {money(s.price)} ({s.duration} min)</option>)}</select></label><label>Trabajadora<select value={form.specialistId} onChange={e=>setForm({...form, specialistId:e.target.value})}>{specialists.map(s=><option key={s.id} value={s.id}>{s.full_name} · {s.categories?.map(c=>c.name).join(', ')}</option>)}</select></label><label>Fecha<input type="date" value={form.date} onChange={e=>setForm({...form, date:e.target.value})}/></label><label>Método de pago<select value={form.paymentMethodId} onChange={e=>setForm({...form, paymentMethodId:e.target.value})}><option value="">Selecciona</option>{paymentMethods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><h3>Horarios disponibles</h3><div className="slots">{slots.map(s=><button key={s.time} disabled={!s.available} className={form.time===s.time?'active':''} onClick={()=>setForm({...form,time:s.time})}>{s.time}{!s.available?' ocupado':''}</button>)}</div><div className="summary"><b>Resumen</b><span>{selected?.name}</span><span>{selected?.duration} min + 15 min descanso</span><strong>{money(selected?.price)}</strong></div><button disabled={!form.time || !form.paymentMethodId} onClick={reserve}>Confirmar reserva</button></section><section className="card list"><h2>Mis reservas</h2>{bookings.map(b=><BookingCard key={b.id} b={b}/>)}</section></div>;
}
function WorkerPanel({ bookings, refresh }) { async function setStatus(id,status){ await api(`/api/bookings/${id}/status`, { method:'PATCH', body: JSON.stringify({ status }) }); refresh(); } return <section className="card list"><h2>Mi trabajo y pagos <BriefcaseBusiness/></h2>{bookings.map(b=><article className="booking" key={b.id}><div><h4>{b.service_name}</h4><p>{new Date(b.starts_at).toLocaleString('es-PE')} · {money(b.price)}</p><small>Cliente: {b.customer_name} · Pago elegido: {b.payment_method || 'por confirmar'}</small></div><em className={b.status}>{b.status}</em><button className="mini" onClick={()=>setStatus(b.id,'in_progress')}>En proceso</button><button className="mini" onClick={()=>setStatus(b.id,'paid')}>Pagado</button><button className="mini" onClick={()=>setStatus(b.id,'cancelled')}>Cancelar</button></article>)}</section>; }
function WorkersAdmin({ categories, refresh }) {
  const [workers,setWorkers]=useState([]); const [editing,setEditing]=useState(null); const [error,setError]=useState('');
  const [form,setForm]=useState({fullName:'',phone:'',email:'',workStart:'09:00',workEnd:'18:00',categoryIds:[]});
  async function loadWorkers(){ setWorkers(await api('/api/admin/workers')); }
  useEffect(()=>{loadWorkers().catch(()=>{})},[]);
  function reset(){ setEditing(null); setForm({fullName:'',phone:'',email:'',workStart:'09:00',workEnd:'18:00',categoryIds:[]}); }
  function toggle(id){ const list=form.categoryIds.includes(id)?form.categoryIds.filter(x=>x!==id):[...form.categoryIds,id]; setForm({...form,categoryIds:list}); }
  function edit(w){ setEditing(w); setForm({fullName:w.full_name || '', phone:w.phone || '', email:w.email || '', workStart:(w.work_start || '09:00').slice(0,5), workEnd:(w.work_end || '18:00').slice(0,5), categoryIds:(w.categories || []).map(c=>c.id)}); }
  async function save(){ setError(''); try { if(editing){ await api(`/api/admin/workers/${editing.id}`,{method:'PATCH',body:JSON.stringify(form)}); } else { await api('/api/admin/workers',{method:'POST',body:JSON.stringify(form)}); } reset(); await loadWorkers(); refresh(); } catch(e){ setError(e.message); } }
  async function active(w,isActive){ setError(''); try { await api(`/api/admin/workers/${w.id}`,{method:'PATCH',body:JSON.stringify({isActive})}); await loadWorkers(); } catch(e){ setError(e.message); } }
  return <div className="two"><section className="card"><h2>{editing ? 'Editar trabajadora' : 'Añadir trabajadora'} <Users/></h2>{error && <strong className="error">{error}</strong>}<div className="formgrid"><input placeholder="Nombres y apellidos" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/><input placeholder="Celular" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="Correo opcional" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="time" value={form.workStart} onChange={e=>setForm({...form,workStart:e.target.value})}/><input type="time" value={form.workEnd} onChange={e=>setForm({...form,workEnd:e.target.value})}/></div><h3>Especialidades</h3><p className="hint">Marca solo las categorías que esta trabajadora atiende. Solo aparecerá en reservas de esas categorías.</p><div className="checks">{categories.map(c=><span key={c.id} onClick={()=>toggle(c.id)} className={form.categoryIds.includes(c.id)?'active':''}><Check size={16}/>{c.name}</span>)}</div><button onClick={save}>{editing ? 'Guardar cambios' : 'Crear usuario automático'}</button>{editing && <button className="ghost" onClick={reset}>Cancelar edición</button>}</section><section className="card list"><h2>Trabajadoras registradas</h2>{workers.map(w=><article className="booking worker-row" key={w.id}><div><h4>{w.full_name}</h4><p>{w.phone} · {w.work_start?.slice(0,5)}-{w.work_end?.slice(0,5)}</p><small>Usuario: {w.dni} · Contraseña: {w.plain_password || 'no visible'}</small><small>Especialidades: {w.categories?.map(c=>c.name).join(', ') || 'Sin especialidades'}</small></div><em className={w.is_active&&w.user_active?'paid':'cancelled'}>{w.is_active&&w.user_active?'activa':'inactiva'}</em><button className="mini" onClick={()=>edit(w)}>Editar especialidades</button><button className="mini" onClick={()=>active(w,!(w.is_active&&w.user_active))}>{w.is_active&&w.user_active?'Suspender':'Reactivar'}</button></article>)}</section></div>; }
function CatalogAdmin({ categories, services, refresh }) {
  const emptyCat = {name:'',description:''};
  const emptySvc = {name:'',description:'',price:'',duration:'',categoryId:''};
  const [cat,setCat]=useState(emptyCat); const [catEditing,setCatEditing]=useState(null);
  const [svc,setSvc]=useState(emptySvc); const [svcEditing,setSvcEditing]=useState(null);
  const [image,setImage]=useState(null); const [error,setError]=useState('');
  function editCat(c){ setCatEditing(c); setCat({name:c.name || '',description:c.description || ''}); }
  function resetCat(){ setCatEditing(null); setCat(emptyCat); }
  async function saveCat(){ setError(''); try { const path=catEditing?`/api/admin/categories/${catEditing.id}`:'/api/admin/categories'; await api(path,{method:catEditing?'PATCH':'POST',body:JSON.stringify(cat)}); resetCat(); refresh(); } catch(e){ setError(e.message); } }
  async function deleteCat(c){ if(!confirm(`¿Eliminar la categoría ${c.name}?`)) return; setError(''); try { await api(`/api/admin/categories/${c.id}`,{method:'DELETE'}); if(catEditing?.id===c.id) resetCat(); refresh(); } catch(e){ setError(e.message); } }
  function editSvc(s){ setSvcEditing(s); setSvc({name:s.name || '',description:s.description || '',price:s.price || '',duration:s.duration || '',categoryId:String(s.category_id || '')}); setImage(null); }
  function resetSvc(){ setSvcEditing(null); setSvc(emptySvc); setImage(null); }
  async function saveSvc(){ setError(''); try { const fd=new FormData(); Object.entries(svc).forEach(([k,v])=>fd.append(k,v)); if(image) fd.append('image',image); await api(svcEditing?`/api/admin/services/${svcEditing.id}`:'/api/admin/services',{method:svcEditing?'PATCH':'POST',body:fd}); resetSvc(); refresh(); } catch(e){ setError(e.message); } }
  async function deleteSvc(s){ if(!confirm(`¿Eliminar el servicio ${s.name}?`)) return; setError(''); try { await api(`/api/admin/services/${s.id}`,{method:'DELETE'}); if(svcEditing?.id===s.id) resetSvc(); refresh(); } catch(e){ setError(e.message); } }
  return <div className="two catalog-admin">{error && <strong className="error full">{error}</strong>}<section className="card"><h2>{catEditing ? 'Editar categoría' : 'Categorías'}</h2><input placeholder="Ej: Maquillaje" value={cat.name} onChange={e=>setCat({...cat,name:e.target.value})}/><textarea placeholder="Descripción" value={cat.description} onChange={e=>setCat({...cat,description:e.target.value})}/><button onClick={saveCat}>{catEditing ? 'Guardar cambios' : 'Guardar categoría'}</button>{catEditing && <button className="ghost" onClick={resetCat}>Cancelar edición</button>}<div className="admin-list">{categories.map(c=><article className="admin-row" key={c.id}><div><b>{c.name}</b><small>{c.description || 'Sin descripción'}</small></div><button className="mini" onClick={()=>editCat(c)}>Editar</button><button className="mini danger" onClick={()=>deleteCat(c)}>Eliminar</button></article>)}</div></section><section className="card"><h2>{svcEditing ? 'Editar servicio' : 'Nuevo servicio'} <Plus/></h2><div className="formgrid"><input placeholder="Título" value={svc.name} onChange={e=>setSvc({...svc,name:e.target.value})}/><input type="number" placeholder="Precio" value={svc.price} onChange={e=>setSvc({...svc,price:e.target.value})}/><input type="number" placeholder="Minutos" value={svc.duration} onChange={e=>setSvc({...svc,duration:e.target.value})}/><select value={svc.categoryId} onChange={e=>setSvc({...svc,categoryId:e.target.value})}><option value="">Categoría</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><textarea placeholder="Descripción breve" value={svc.description} onChange={e=>setSvc({...svc,description:e.target.value})}/><label className="upload file-upload"><ImageIcon/><b>{image?.name || (svcEditing?.image_url ? 'Cambiar imagen referencial' : 'Imagen referencial')}</b><input type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0] || null)}/></label><button onClick={saveSvc}>{svcEditing ? 'Guardar cambios' : 'Guardar servicio'}</button>{svcEditing && <button className="ghost" onClick={resetSvc}>Cancelar edición</button>}<div className="admin-list">{services.map(s=><article className="admin-row" key={s.id}>{s.image_url && <img src={s.image_url} alt={s.name}/>}<div><b>{s.name}</b><small>{money(s.price)} · {s.duration} min · {s.category_name || s.category}</small></div><button className="mini" onClick={()=>editSvc(s)}>Editar</button><button className="mini danger" onClick={()=>deleteSvc(s)}>Eliminar</button></article>)}</div></section></div>; }
function Admin(){ const [revenue,setRevenue]=useState([]); const [selected,setSelected]=useState(null); useEffect(()=>{api('/api/admin/revenue').then(rows=>{setRevenue(rows); setSelected(rows[0] || null);}).catch(()=>{})},[]); const detail=selected || revenue[0]; return <div className="two admin"><section className="card list"><h2>Ganancias por trabajadora</h2>{revenue.map(r=><article className={`worker-summary ${detail?.id===r.id?'active':''}`} key={r.id} onClick={()=>setSelected(r)}><h3>{r.full_name}</h3><p>Hoy: <b>{money(r.today)}</b></p><p>Total histórico: <b>{money(r.total)}</b></p><small>{Number(r.today_jobs || 0)} reserva{Number(r.today_jobs || 0)===1?'':'s'} atendida{Number(r.today_jobs || 0)===1?'':'s'} hoy</small></article>)}</section><section className="card worker-detail"><h2>{detail ? `Detalle de ${detail.full_name}` : 'Detalle'}</h2>{detail ? <><div className="detail-kpis"><b>{Number(detail.today_jobs || 0)}<small>Reservas hoy</small></b><b>{money(detail.today)}<small>Generado hoy</small></b><b>{money(detail.total)}<small>Total histórico</small></b></div><h3>Trabajos</h3>{(detail.jobs || []).length ? detail.jobs.map((j,i)=><article className="job-row" key={j.id || i}><div><b>{j.service}</b><small>{j.starts_at ? new Date(j.starts_at).toLocaleString('es-PE') : ''}</small></div><span>{money(j.price)}</span><em className={j.status}>{j.payment || 'sin método'} · {j.status}</em></article>) : <p className="hint">Aún no tiene reservas registradas.</p>}</> : <p className="hint">Selecciona una trabajadora.</p>}</section></div>; }
function AiPage({ quote, setQuote }) { const [hints, setHints] = useState('acrílico con piedras y efecto espejo para boda'); const [image, setImage] = useState(null); const [loading, setLoading] = useState(false); async function makeQuote(){ setLoading(true); const form = new FormData(); form.append('hints', hints); if (image) form.append('image', image); try { setQuote(await api('/api/quotes/ai', { method:'POST', body: form })); } catch { setQuote({ difficulty:'Media', estimatedMinutes:95, price:95, materials:['Nail Art'], explanation:'Demo local', source:'demo' }); } finally { setLoading(false); } } return <div className="two"><section className="card quote"><h2>Cotizar diseño con IA <Sparkles/></h2><textarea value={hints} onChange={e=>setHints(e.target.value)}/><label className="upload file-upload"><ImageIcon/><b>{image ? image.name : 'Imagen referencial'}</b><input type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0] || null)}/></label><button onClick={makeQuote} disabled={loading}>{loading ? 'Analizando...' : 'Analizar diseño'}</button></section>{quote && <section className="card result"><h2>Resultado <span>{quote.source}</span></h2><p>Dificultad <b>{quote.difficulty}</b></p><p>Tiempo <b>{quote.estimatedMinutes} min</b></p><p>Precio <strong>{money(quote.price)}</strong></p><p>{quote.explanation}</p></section>}</div>; }
function AiAssistant() { const [message, setMessage] = useState('¿Qué horarios tiene Valeria?'); const [reply, setReply] = useState('Pregúntame por precios, horarios, trabajadoras y reservas.'); const [loading, setLoading] = useState(false); async function ask(){ if(!message.trim()) return; setLoading(true); try { const data = await api('/api/assistant', { method:'POST', body: JSON.stringify({ message }) }); setReply(data.aiWarning ? `${data.reply} (${data.aiWarning})` : data.reply); } catch { setReply('Configura GEMINI_API_KEY para respuestas inteligentes.'); } finally { setLoading(false); } } return <section className="card result chat"><h2>Asistente virtual <MessageCircle/></h2><p>{reply}</p><div className="chat-row"><input value={message} onChange={e=>setMessage(e.target.value)} /><button onClick={ask} disabled={loading}>{loading ? '...' : 'Enviar'}</button></div></section>; }
function BookingCard({ b }) { return <article className="booking"><div><h4>{b.service_name || b.name || 'Servicio'}</h4><p>{b.starts_at ? new Date(b.starts_at).toLocaleString('es-PE') : ''} · {money(b.price)}</p><small>con {b.specialist_name || 'Trabajadora'} · Pago: {b.payment_method || 'por confirmar'}</small></div><em className={b.status}>{b.status}</em></article>; }
function Catalog({ services }) { const [category,setCategory]=useState(null); const groups=services.reduce((acc,s)=>{ const name=s.category_name || s.category || 'Otros'; acc[name]=acc[name]||[]; acc[name].push(s); return acc; },{}); const names=Object.keys(groups).sort(); if(category) return <section className="card catalog"><h2><span>{category}</span><a onClick={()=>setCategory(null)}>Volver a categorías</a></h2><div>{(groups[category]||[]).map(s=><article className="service" key={s.id}>{s.image_url && <img src={s.image_url} alt={s.name}/>}<h4>{s.name}</h4><p>{money(s.price)} · {s.duration} min</p><small>{s.description}</small></article>)}</div></section>; return <section className="card catalog"><h2>Catálogo de servicios</h2><div className="category-grid">{names.map(name=><button className="category-card" key={name} onClick={()=>setCategory(name)}><strong>{name}</strong><small>{groups[name].length} servicio{groups[name].length===1?'':'s'}</small></button>)}</div></section>; }
function Profile({ user }) { return <section className="card"><h2>Mi perfil <User/></h2><p><b>DNI/usuario:</b> {user.dni}</p><p><b>Nombre:</b> {user.full_name}</p><p><b>Rol:</b> {user.role}</p></section>; }
function Payments() { return <section className="card"><h2>Pagos <CreditCard/></h2>{['Pago en local','Tarjeta','Yape','Plin','Transferencia'].map(x=><p className="pay" key={x}><Check/> {x}</p>)}</section>; }
createRoot(document.getElementById('root')).render(<App/>);
