import React from 'react';
import { createRoot } from 'react-dom/client';
import { Calendar, Camera, Gift, Bell, User, Menu, Sparkles, Star, Check, CreditCard, MessageCircle, BarChart3 } from 'lucide-react';
import './styles.css';

const services = [
  ['Manicure básica', 'Desde S/ 40', 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=500&q=80'],
  ['Manicure en gel', 'Desde S/ 60', 'https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=500&q=80'],
  ['Acrílicas', 'Desde S/ 80', 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=500&q=80'],
  ['Nail Art', 'Desde S/ 30', 'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=500&q=80'],
  ['Pedicure spa', 'Desde S/ 70', 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=500&q=80'],
  ['Soft Gel', 'Desde S/ 60', 'https://images.unsplash.com/photo-1599948128020-9a44505b0d1b?auto=format&fit=crop&w=500&q=80'],
];
const bookings = [['MAY','24','Manicure en gel con decoración','3:00 PM','Valeria','Confirmada'], ['MAY','31','Acrílicas + Nail Art','4:30 PM','Daniela','Pendiente'], ['JUN','07','Pedicure spa','11:00 AM','Valeria','Confirmada']];
const nav = [['Inicio', Calendar], ['Mis reservas', Calendar], ['Cotizar diseño con IA', Camera], ['Mis diseños', Sparkles], ['Mis puntos', Gift], ['Pagos', CreditCard], ['Perfil', User]];

function Sidebar(){return <aside className="sidebar"><div className="brand">Nail·Beauty<small>Salón de belleza</small></div><nav>{nav.map(([n,Icon],i)=><a className={i===0?'active':''} href="#" key={n}><Icon size={18}/>{n}{n==='Mis puntos'&&<b>250</b>}</a>)}</nav><div className="birthday"><Gift/><h3>¡Feliz cumpleaños Andrea!</h3><p>Tienes un manicure BÁSICO GRATIS</p><button>Reservar ahora</button><small>Válido hasta 31/05/2026</small></div></aside>}
function Topbar(){return <header className="topbar"><button className="hamb"><Menu/></button><a>Inicio</a><a>Servicios</a><a>Galería</a><a>Promociones</a><a>Nosotras</a><a>Contacto</a><span/><Bell/><div className="avatar">A</div><strong>Hola, Andrea</strong></header>}
function BookingCard({b}){return <article className="booking"><div className="date"><span>{b[0]}</span><strong>{b[1]}</strong><small>SÁB</small></div><img src="https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=180&q=80"/><div><h4>{b[2]}</h4><p>◷ {b[3]}</p><small>con {b[4]}</small></div><em className={b[5]}>{b[5]}</em></article>}
function ServiceCard({s}){return <article className="service"><img src={s[2]}/><h4>{s[0]}</h4><p>{s[1]}</p></article>}
function AiQuote(){return <section className="card quote"><h2>Cotiza tu diseño con IA <Sparkles size={18}/></h2><p>Sube una imagen de las uñas que deseas y obtén tu cotización al instante.</p><div className="upload"><Camera/><b>Subir imagen</b><small>o arrastra tu imagen aquí</small></div><button>Cotizar con IA</button></section>}
function QuoteResult(){return <section className="card result"><h2>Resultado de tu cotización <span>IA ✨</span></h2><img src="https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=700&q=80"/><p>Nivel de dificultad <span className="stars"><Star/><Star/><Star/><Star/></span></p><p>Tiempo estimado <b>2h 15m</b></p><p>Precio aproximado <strong>S/ 130</strong></p><div className="checks">{['Acrílico','Nail Art','Piedras','Esmalte permanente'].map(x=><span><Check size={16}/>{x}</span>)}</div><button>Reservar este diseño</button></section>}
function MobilePreview(){return <div className="phone"><div className="mobileTop"><Menu/> <div className="brand">Nail·Beauty</div><Bell/><div className="avatar">A</div></div><h2>¡Hola, Andrea! 👋</h2><p>¿Qué te gustaría hacer hoy?</p><div className="quick"><button><Calendar/>Reservar cita</button><button><Camera/>Cotizar diseño con IA</button><button><Calendar/>Mis reservas</button></div><div className="banner"><b>¡Feliz cumpleaños!</b><p>Tienes un manicure BÁSICO GRATIS</p><button>Usar mi beneficio</button></div><h3>Próxima cita <a>Ver todas</a></h3><BookingCard b={bookings[0]}/><footer>{nav.slice(0,4).map(([n,Icon])=><a><Icon/>{n.split(' ')[0]}</a>)}</footer></div>}
function App(){return <main className="shell"><Sidebar/><section className="workspace"><Topbar/><div className="grid"><section className="hero"><div><h1>Reserva tu cita</h1><p>Elige el servicio, la fecha y la hora que mejor se adapte a ti.</p><button>Reservar ahora <Calendar size={18}/></button></div></section><AiQuote/><section className="card list"><h2>Próximas reservas <a>Ver todas</a></h2>{bookings.map(b=><BookingCard b={b}/>)}</section><section className="card catalog"><h2>Catálogo de servicios <a>Ver todas</a></h2><div>{services.map(s=><ServiceCard s={s}/>)}</div></section><QuoteResult/><section className="why"><h2>¿Por qué elegirnos?</h2>{['Profesionales especializadas','Productos de alta calidad','Ambiente seguro y moderno','Atención personalizada'].map(x=><span><Sparkles/>{x}</span>)}</section><section className="card loyalty"><h2>🏆 Nivel Oro <b>250 pts</b></h2><progress value="50" max="100"/><p>Te faltan 250 puntos para ser nivel Diamante 💎.</p></section></div></section></main>}

createRoot(document.getElementById('root')).render(<App/>);
